version: "3.8"
services: 
  app:
    build: .
    volumes:
      - .:/django_docker
    ports:
      - 8080:8080
    image: app:django_docker_basic_image
    container_name: django_docker_basic_container
    command: python manage.py runserver 0.0.0.0:8080